"""init tables

Revision ID: 221b3906ca4e
Revises: 
Create Date: 2023-01-16 01:16:16.741141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221b3906ca4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.Column('right_answer', sa.String(), nullable=False),
    sa.Column('wrong_answer1', sa.String(), nullable=False),
    sa.Column('wrong_answer2', sa.String(), nullable=False),
    sa.Column('wrong_answer3', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['test'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_test'), 'questions', ['test'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('current_question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_question'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_index(op.f('ix_questions_test'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('tests')
    # ### end Alembic commands ###
